name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Create and switch to gh-pages branch
        run: |
          git checkout -B gh-pages

      - name: Rename simulation.html to index.html
        run: |
          cp simulation.html index.html

      - name: Clean up unneeded files
        run: |
          ls | grep -v -e 'index.html' -e 'simulation.js' -e 'simulation.data' -e 'simulation.wasm' -e 'favicon.svg' | xargs rm -rf

      - name: Commit and push to gh-pages
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git add .
          git commit -m "Update files from main"
          git push https://x-access-token:${TOKEN}@github.com/sanchezhs/particle-simulation.git gh-pages --force
